import { Montserrat, Cormorant_Garamond } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import localFont from 'next/font/local'
import '../globals.scss'

// internal imports
import Wrapper from '@/layouts/wrapper'
import HeaderEleven from '@/layouts/headers/header-eleven'
import FooterTwo from '@/layouts/footers/footer-two'

const ivy = localFont({
  src: [
    {
      path: '../../public/assets/fonts/IvyMode-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/assets/fonts/IvyMode-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--tp-ff-ivy',
})

const montserrat = Montserrat({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--tp-ff-montserrat',
})

const cormorant = Cormorant_Garamond({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--tp-ff-cormorant',
})

export const metadata = {
  title: 'Gerczew Stomatologia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pl" suppressHydrationWarning={true}>
      <head>
        <link
          rel="preload"
          href="https://use.typekit.net/dka5wda.css"
          as="font"
        />
        <link rel="stylesheet" href="https://use.typekit.net/dka5wda.css" />
      </head>
      <body
        id="body"
        suppressHydrationWarning={true}
        className={`${montserrat.variable} ${cormorant.variable}`}
      >
        <ThemeProvider defaultTheme="light">
          <Wrapper>
            {/* header area start */}
            <HeaderEleven />
            <div id="smooth-wrapper">
              <div id="smooth-content">
                <main>
                  {children}
                  <FooterTwo />
                </main>
                {/* footer area */}
                {/* <FooterTwo topCls="" /> */}
                {/* footer area */}
              </div>
            </div>
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  )
}
